defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>1"

pull_request_rules:
  - name: Backport patches to the v0.37.x branch
    conditions:
      - base=main
      - label=A:backport/v0.37.x
    actions:
      backport:
        branches:
          - release/v0.37.x
  - name: Backport patches to the v0.34.x branch
    conditions:
      - base=main
      - label=A:backport/v0.34.x
    actions:
      backport:
        branches:
          - release/v0.34.x
