defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

pull_request_rules:
  - name: Backport patches to the v0.38.x branch
    conditions:
      - base=main
      - label=A:backport/v0.38.x
    actions:
      backport:
        branches:
          - v0.38.x
  - name: Backport patches to the v0.37.x branch
    conditions:
      - base=main
      - label=A:backport/v0.37.x
    actions:
      backport:
        branches:
          - v0.37.x
  - name: Backport patches to the v0.34.x branch
    conditions:
      - base=main
      - label=A:backport/v0.34.x
    actions:
      backport:
        branches:
          - v0.34.x
