# import simd from ibc-go

FROM golang:1.20-alpine as cometmock-builder

ENV PACKAGES curl make git libc-dev bash gcc linux-headers
RUN apk add --no-cache $PACKAGES

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOFLAGS="-buildvcs=false"

# cache gomodules for cometmock
ADD ./go.mod /go.mod
ADD ./go.sum /go.sum
RUN go mod download

# Add CometMock and install it
ADD . /CometMock
WORKDIR /CometMock
RUN go build -o /usr/local/bin/cometmock ./cometmock

FROM ghcr.io/cosmos/simapp:v0.47
RUN apk update
RUN apk add --no-cache which iputils procps-ng tmux net-tools htop jq gcompat

COPY --from=cometmock-builder /usr/local/bin/cometmock /usr/local/bin/cometmock

COPY . /CometMock

