#!/bin/bash

## Starts the testnet, assuming that the scripts generated by local-testnet-singlechain-setup.sh
## are already present in the current directory.

COMETMOCK_ARGS=$1

./start_apps.sh
./start_cometmock.sh "$1"